<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                <img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="ZF2-NAVIGATION"/>&nbsp;
                    <?php echo $this->translate('YOUR SITE NAME') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <?php
            echo $this->navigation('top_nav')
                    ->menu()
                    ->setUlClass('nav navbar-nav')
                    ->setPartial('partial/horizontal.phtml');
            ?>
        </div>
    </div>
</nav>